# Generated by Django 3.2.3 on 2023-08-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20230809_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
